// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
lv_chart_series_t* ui_Chart1_series_1 ;
lv_chart_series_t* ui_Chart2_series_1 ;
#define BUFSIZE 128
extern lv_coord_t array[BUFSIZE]; 


void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Chart1 = lv_chart_create(ui_Screen1);
lv_obj_set_width( ui_Chart1, 200);
lv_obj_set_height( ui_Chart1, 100);
lv_obj_set_x( ui_Chart1, -118 );
lv_obj_set_y( ui_Chart1, -2 );
lv_obj_set_align( ui_Chart1, LV_ALIGN_CENTER );
lv_chart_set_type( ui_Chart1, LV_CHART_TYPE_LINE);
lv_chart_set_range( ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 0, 40);
lv_chart_set_range( ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 40);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, false, 50);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 4, 2, false, 50);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 4, 2, false, 25);
lv_chart_series_t* ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_Chart1_series_1_array[] = { 0,0,0,0,0,0,0,0,0,0 };
lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);

//Ë¢ÐÂ·½Ê½
lv_chart_set_update_mode(ui_Chart1,LV_CHART_UPDATE_MODE_SHIFT);


ui_Chart2 = lv_chart_create(ui_Screen1);
lv_obj_set_width( ui_Chart2, 200);
lv_obj_set_height( ui_Chart2, 100);
lv_obj_set_x( ui_Chart2, 112 );
lv_obj_set_y( ui_Chart2, -1 );
lv_obj_set_align( ui_Chart2, LV_ALIGN_CENTER );
lv_chart_set_type( ui_Chart2, LV_CHART_TYPE_LINE);
lv_chart_set_range( ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, -32767, 32767);
lv_chart_set_axis_tick( ui_Chart2, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, false, 50);
lv_chart_set_axis_tick( ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, false, 50);
lv_chart_set_axis_tick( ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
lv_chart_series_t* ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0xD41E1E), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_Chart2_series_1_array[] = { 0,0,0,0,0,0,0,0,0,0 };
lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);



ui_Dropdown1 = lv_dropdown_create(ui_Screen1);
lv_dropdown_set_options( ui_Dropdown1, "1\n5\n10" );
lv_obj_set_width( ui_Dropdown1, 100);
lv_obj_set_height( ui_Dropdown1, 30);
lv_obj_set_x( ui_Dropdown1, -170 );
lv_obj_set_y( ui_Dropdown1, 90 );
lv_obj_set_align( ui_Dropdown1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Dropdown1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags



lv_obj_add_event_cb(ui_Dropdown1, ui_event_Dropdown1, LV_EVENT_ALL, NULL);

}
